name: Herbal Garden
favicon: null
layout_spectrum: 0.8608056160155684
typography_spectrum: 0.90874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8cd98'
    - '#ba9f6a'
    - '#866b36'
    - '#4d3615'
  brandStrength: 0.7095925232861191
  lightness: 0.28715607058256865
  saturation: 0.38393490645103157
  rhythmicContrast: 0.5670290305279195
purpose: []
