name: "Greta's secret herbal garden"
favicon: null
layout_spectrum: 0.45973
typography_spectrum: 0.29088
title: "Greta's secret herbal garden"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f8f7'
    - '#878787'
    - '#c2c9c1'
    - '#4b9500'
    - '#8dc433'
  brandStrength: 0.7095925232861191
  lightness: 0.28715607058256865
  saturation: 0.38393490645103157
  rhythmicContrast: 0.5670290305279195
purpose: []
